(function () {
  var nav = document.querySelector('.site-nav');
  var footer = document.querySelector('.site-footer');
  var input = document.querySelector('.site-nav-search');
  var dropdown = document.querySelector('.search-dropdown');
  if (!nav || !input || !dropdown) return;

  var activeIndex = -1;

  // Fixed footer on desktop, static on mobile (iOS keyboard breaks fixed/sticky)
  var isTouch = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
  if (!isTouch && footer) {
    footer.style.position = 'fixed';
    footer.style.bottom = '0';
    footer.style.left = '0';
    footer.style.right = '0';
    footer.style.zIndex = '9999';
    document.body.style.paddingBottom = footer.offsetHeight + 'px';
  }

  function loadAsset(tag, url, integrity, onload) {
    var el = document.createElement(tag);
    if (tag === 'link') { el.rel = 'stylesheet'; el.href = url; } else { el.src = url; }
    el.integrity = integrity;
    el.crossOrigin = 'anonymous';
    if (onload) el.onload = onload;
    document.head.appendChild(el);
  }

  // search.json is generated by build.js: one entry per post with title, meta, body
  var indexPromise = null;
  function getIndex() {
    if (!indexPromise) {
      indexPromise = fetch('/search.json').then(function (r) { return r.json(); }).catch(function () { return []; });
    }
    return indexPromise;
  }

  // --- Random ---
  function getHistory() {
    try { return JSON.parse(sessionStorage.getItem('rh') || '{}'); } catch (e) { return {}; }
  }
  function saveHistory(h) {
    try { sessionStorage.setItem('rh', JSON.stringify(h)); } catch (e) {}
  }

  var randomBtn = nav.querySelector('.site-nav-random');
  if (randomBtn) {
    randomBtn.addEventListener('click', function (e) {
      e.preventDefault();
      getIndex().then(function (items) {
        var posts = items.map(function (it) { return it.href; });
        if (!posts.length) return;
        var history = getHistory();
        var current = window.location.pathname;

        posts.forEach(function (p) {
          if (history[p] === undefined) history[p] = posts.length;
          else history[p]++;
        });

        var weights = posts.map(function (p) {
          if (p === current) return 0;
          var w = history[p] || 1;
          return w * w;
        });
        var totalWeight = weights.reduce(function (a, b) { return a + b; }, 0);
        if (totalWeight === 0) { weights = posts.map(function () { return 1; }); totalWeight = posts.length; }

        var r = Math.random() * totalWeight;
        var pick = posts[0];
        for (var i = 0; i < posts.length; i++) {
          r -= weights[i];
          if (r <= 0) { pick = posts[i]; break; }
        }

        history[pick] = 0;
        saveHistory(history);
        window.location.href = pick;
      });
    });
  }

  // --- Full-text fuzzy search with Fuse.js ---
  var fuse = null;
  var fuseReady = null;

  function ensureFuse() {
    if (fuseReady) return fuseReady;
    fuseReady = new Promise(function (resolve) {
      loadAsset('script', 'https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js',
        'sha384-PCSoOZTpbkikBEtd/+uV3WNdc676i9KUf01KOA8CnJotvlx8rRrETbDuwdjqTYvt', resolve);
    }).then(getIndex).then(function (items) {
      fuse = new Fuse(items, {
        keys: [
          { name: 'title', weight: 3 },
          { name: 'meta', weight: 2 },
          { name: 'body', weight: 1 }
        ],
        includeMatches: true,
        threshold: 0.3,
        ignoreLocation: true,
        minMatchCharLength: 2
      });
      return fuse;
    });
    return fuseReady;
  }

  // --- Search UI ---
  function getSnippet(text, query, maxLen) {
    maxLen = maxLen || 120;
    var lower = text.toLowerCase();
    var words = query.toLowerCase().split(/\s+/).filter(Boolean);
    var bestPos = -1;
    for (var i = 0; i < words.length; i++) {
      var pos = lower.indexOf(words[i]);
      if (pos !== -1 && (bestPos === -1 || pos < bestPos)) bestPos = pos;
    }
    if (bestPos === -1) return '';
    var start = Math.max(0, bestPos - 40);
    var end = Math.min(text.length, start + maxLen);
    if (start > 0) start = text.indexOf(' ', start) + 1 || start;
    var snippet = (start > 0 ? '...' : '') + text.slice(start, end).trim() + (end < text.length ? '...' : '');
    words.forEach(function (w) {
      if (w.length < 2) return;
      snippet = snippet.replace(new RegExp('(' + w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'gi'), '<mark>$1</mark>');
    });
    return snippet;
  }

  function escapeHtml(s) {
    var div = document.createElement('div');
    div.textContent = s;
    return div.innerHTML;
  }

  function showResults(query) {
    if (!query || !fuse) {
      dropdown.classList.remove('open');
      dropdown.innerHTML = '';
      activeIndex = -1;
      return;
    }
    var results = fuse.search(query, { limit: 8 });
    if (!results.length) {
      dropdown.innerHTML = '<div class="search-empty">No results</div>';
      dropdown.classList.add('open');
      activeIndex = -1;
      return;
    }
    dropdown.innerHTML = results.map(function (r) {
      var item = r.item;
      var snippet = getSnippet(item.body, query);
      return '<a href="' + item.href + '" class="search-result" role="option">' +
        '<div class="search-result-title">' + escapeHtml(item.title) + '</div>' +
        '<div class="search-result-meta">' + escapeHtml(item.meta) + '</div>' +
        (snippet ? '<div class="search-result-context">' + snippet + '</div>' : '') +
        '</a>';
    }).join('');
    dropdown.classList.add('open');
    activeIndex = -1;
  }

  function setActive(index) {
    var items = dropdown.querySelectorAll('.search-result');
    items.forEach(function (el, i) { el.classList.toggle('active', i === index); });
    activeIndex = index;
    if (items[index]) items[index].scrollIntoView({ block: 'nearest' });
  }

  function search(q) {
    if (q.length < 2) { dropdown.classList.remove('open'); dropdown.innerHTML = ''; activeIndex = -1; return; }
    ensureFuse().then(function () {
      if (input.value.trim() === q) showResults(q);
    });
  }

  input.addEventListener('focus', function () { ensureFuse(); });
  input.addEventListener('input', function () { search(this.value.trim()); });

  input.addEventListener('keydown', function (e) {
    var items = dropdown.querySelectorAll('.search-result');
    if (e.key === 'ArrowDown') { e.preventDefault(); setActive(Math.min(activeIndex + 1, items.length - 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setActive(Math.max(activeIndex - 1, 0)); }
    else if (e.key === 'Enter') {
      e.preventDefault();
      if (activeIndex >= 0 && items[activeIndex]) window.location.href = items[activeIndex].getAttribute('href');
      else if (items.length > 0) window.location.href = items[0].getAttribute('href');
    }
  });

  document.addEventListener('click', function (e) {
    if (!nav.querySelector('.site-nav-controls').contains(e.target)) {
      dropdown.classList.remove('open');
      activeIndex = -1;
    }
  });

  // --- iOS Safari keyboard dismiss fix ---
  // Forces viewport recalculation after virtual keyboard closes
  document.addEventListener('focusout', function () {
    setTimeout(function () { window.scrollBy(0, 0); }, 100);
  });

  // --- Keyboard shortcuts ---
  document.addEventListener('keydown', function (e) {
    var tag = (document.activeElement || {}).tagName;
    if (e.key === '/' && tag !== 'INPUT' && tag !== 'TEXTAREA') { e.preventDefault(); input.focus(); }
    if (e.key === 'Escape') { input.value = ''; input.blur(); dropdown.classList.remove('open'); dropdown.innerHTML = ''; activeIndex = -1; }
  });

  // --- KaTeX math rendering (lazy-loaded) ---
  var mathContent = document.body.textContent;
  if (mathContent.indexOf('\\(') !== -1 || mathContent.indexOf('\\[') !== -1) {
    var katex = 'https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/';
    loadAsset('link', katex + 'katex.min.css',
      'sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP');
    loadAsset('script', katex + 'katex.min.js',
      'sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6', function () {
        loadAsset('script', katex + 'contrib/auto-render.min.js',
          'sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh', function () {
            renderMathInElement(document.body, {
              delimiters: [
                { left: '\\[', right: '\\]', display: true },
                { left: '\\(', right: '\\)', display: false }
              ],
              throwOnError: false
            });
          });
      });
  }

  // --- Homepage search from query param ---
  var isHome = window.location.pathname === '/' || window.location.pathname === '/index.html';
  if (isHome) {
    var q = new URLSearchParams(window.location.search).get('q');
    if (q) {
      input.value = q;
      ensureFuse().then(function () { showResults(q); input.focus(); });
    }
  }
})();
